### PR TITLE
Upgrade to Celery 4 - ITINF-1779

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by nikolas** [comment]
@sdreher the error here has been fixed by making the `Operation` model JSON-serializable. 

Also, I've added a rabbitmq service to the GitHub Action build so the tests don't hang.

**Comment by nikolas** [comment]
@sdreher I've reviewed your changes and it looks good. Merge whenever you're ready. I didn't know about the router stuff!

**Comment by sdreher** [comment]
@nikolas - thank you. Can you cast your eye on [these last few changes]( https://github.com/ccnmtl/wardenclyffe/pull/2172/commits/ad23d6eda779b156555a5b99032d3f7c962fe833)?

**Comment by nikolas** [comment]
Yeah - looks good.

**Pull request merged**
